### PR TITLE
Add RequireLastPushApproval

### PR DESCRIPTION
**Pull request by haydentherapper**
This will mitigate insider risk where a maintainer can go to any open PR, modify the contents, and approve and merge the PR. This is effectively self-approval and bypasses the minimum of 1 reviewer check, since the maintainer the entire PR without another review. This check will require that the PR approver be different than the author on the last commit.

See https://github.blog/changelog/2022-10-20-new-branch-protections-last-pusher-and-locked-branch/#require-approval-from-someone-other-than-the-last-pusher for more information

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @cpanato

**Comment by haydentherapper** [comment]
Bumping

**Review by cpanato — COMMENTED** [review]
Will review tomorrow

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
